name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  # github Secrets for UserName
  DOCKER_USER: ${{ secrets.Docker_User }}
  #github Secrets for UserName
  DOCKER_PASSWORD: ${{ secrets.Docker_Password }}
  # APP-Name
  DOCKER_APP: cloudvorlesung-app


jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3

    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the Docker image
      run: docker build ./Docker-Build -t $DOCKER_USER/$DOCKER_APP:$(date +%s)
      
    - name: Push to Docker Hub
      run: docker push legendarsword/cloudvorlesung-app:$(date +%s)
